// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdwcidnolhwoxsettqqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd2NpZG5vbGh3b3hzZXR0cXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDExMzAsImV4cCI6MjA2Njc3NzEzMH0.gxP0G7OcA0Zr23WlsJe29dnYs5dW-eaSKS5X4Brf_Cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});